apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
# images: declares the names overridable by `installer wizard
# --set-image` and `installer upgrade --set-image`. The default values
# match what's hard-coded in deployment.yaml.
images:
  - name: nginxdemos/hello
    newName: nginxdemos/hello
    newTag: plain-text
