apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds/inference.networking.k8s.io_inferencepools.yaml
  - crds/inference.networking.x-k8s.io_inferencemodelrewrites.yaml
  - crds/inference.networking.x-k8s.io_inferenceobjectives.yaml
  - crds/inference.networking.x-k8s.io_inferencepoolimports.yaml
