apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Ingress
      name: hello-app
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          cert-manager.io/cluster-issuer: letsencrypt-prod
      - op: add
        path: /spec/tls
        value:
          - hosts:
              - hello.local
            secretName: hello-app-tls
