apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - crds/ray.io_rayclusters.yaml
  - crds/ray.io_raycronjobs.yaml
  - crds/ray.io_rayjobs.yaml
  - crds/ray.io_rayservices.yaml
  - operator/service_account.yaml
  - operator/role.yaml
  - operator/role_binding.yaml
  - operator/leader_election_role.yaml
  - operator/leader_election_role_binding.yaml
  - operator/manager.yaml
  - operator/service.yaml
