apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- serviceaccount.yaml
- clusterrolebinding.yaml
- deployment.yaml
configMapGenerator:
- envs:
  - confighub-worker.env
  name: confighub-worker-env
  options:
    annotations:
      installer.confighub.com/toolchain: AppConfig/Env
secretGenerator:
- envs:
  - confighub-worker-secret.env.secret
  name: confighub-worker-secret
generatorOptions:
  disableNameSuffixHash: true
images:
- name: ghcr.io/confighubai/confighub-worker
  newTag: v0.1.42
